controller_list:
  - name: fake_snake_arm_controller
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_end_effector_controller
    joints:
      - joint_6